# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25825edc5855e30f4c604d31bbab865b6c7eb0b3b868965a131e144ab0a091c95b5eeb3151744d1af11ccd451a98bd78ed0947a4b9c86758b6d8c49b6b161ba1

test:
  secret_key_base: 8a5b9663a9ced068e579e5922ee8219bcf2e95cf9e1488607fb0db650dd3b54478dc02f50acf0f9b5196b98ff9d0e23298f704fb6ea53a4eee60b990c1ae36a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
